check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.33.0
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: investigator
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: thoth-station
  project-name: thoth-application
  image-name: investigator
  overlay-contextpath: core/overlays/test/imagestreamtags.yaml
